[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheck = "/health"
healthcheckTimeout = 10
healthcheckInterval = 10

[[ports]]
port = "3000"
protocol = "http"