[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheck = "/health"
healthcheckTimeout = 30
healthcheckInterval = 15
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[[ports]]
port = "3000"
internalPort = "3000"

[deploy.env]
NODE_ENV = "production"