[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheck = "/"
healthcheckTimeout = 100
restartPolicy = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
internal_port = 3000
protocol = "http"