[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 15
restartPolicyType = "ON_FAILURE"
healthcheckProtocol = "http"
restartPolicyMaxRetries = 5

[[ports]]
port = "8080"
protocol = "http"
internalPort = "8080"

[variables]
PORT = "8080"
NODE_ENV = "production"