[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheck = "/"
restartPolicy = "ON_FAILURE"
numReplicas = 1

[[services]]
internal_port = 3000
protocol = "http"