[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 10
healthcheckInterval = 5
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[ports]]
port = "8080"
protocol = "http"
internalPort = "8080"

[variables]
PORT = "8080"
NODE_ENV = "production"