[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 10
healthcheckInterval = 10
restartPolicyType = "ON_FAILURE"

[[ports]]
port = "8080"
protocol = "http"

[variables]
PORT = "8080"
NODE_ENV = "production"
REACT_APP_API_URL = "https://address-comparator-backend-production.up.railway.app"